# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField()),
                ('product_unit', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplier_name', models.CharField(max_length=50)),
                ('suplier_address', models.CharField(max_length=100)),
                ('suplier_contact', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='stockin',
            name='suplier_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims_app.Suplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductCompany'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductGroup'),
        ),
    ]
