# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sell_price', models.FloatField()),
                ('stock_in_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.StockIn')),
            ],
        ),
    ]
