# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0002_stockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_contact', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='suplier_info',
        ),
        migrations.DeleteModel(
            name='Suplier',
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ims_app.Supplier'),
        ),
    ]
