# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0003_auto_20170410_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(max_length=100),
        ),
    ]
