# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0004_auto_20170410_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductCompany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductGroup'),
        ),
    ]
