# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0005_auto_20170410_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='updated_date',
        ),
    ]
