# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0006_remove_stockin_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='product_info',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='stockin',
            name='product_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductCompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockin',
            name='product_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims_app.ProductGroup'),
            preserve_default=False,
        ),
    ]
