# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0008_auto_20170411_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
