# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0009_auto_20170411_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
