# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0010_supplier_supplier_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='created_date',
            new_name='stockin_date',
        ),
        migrations.AddField(
            model_name='stockout',
            name='stockout_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims_app.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcompany',
            table='product_company',
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='stockin',
            table='stock_in',
        ),
        migrations.AlterModelTable(
            name='stockout',
            table='stock_out',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='supplier',
        ),
    ]
