# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0011_auto_20170415_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='product_name',
            new_name='product_info',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='product_company',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='product_group',
        ),
    ]
