# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0012_auto_20170415_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_app.StockIn')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
