# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_app', '0013_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='available_stock',
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
